[package]
name = "rsi-war"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.6"
chrono = "0.4"
hhmmss = "0.1"
tui = "0.15"
thiserror = "1.0"


